name: Generate Snake

on:
#  schedule:
#    - cron: "0 2 * * *" 
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: shinkai-tester
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00BFFF&color_dots=#A9A9A9,#551A8B,#551A8B,#551A8B,#551A8B&background_color=black

      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
